/**
 * MiMQIP API
 * Endpoints for the MiMQIP API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface PatientDto {
    id?: number;

    firstName?: string;

    lastName?: string;

    sex?: PatientDto.SexEnum;

    dateOfBirth?: Date;

    valid?: boolean;

    zipCode?: string;

    race?: Array<PatientDto.RaceEnum>;

    ethnicity?: PatientDto.EthnicityEnum;

    marital?: PatientDto.MaritalEnum;

    living?: PatientDto.LivingEnum;

    employment?: PatientDto.EmploymentEnum;

    primaryCarePhysicianName?: string;

    primaryCarePhysicianEmail?: string;

    startDate?: Date;

}
export namespace PatientDto {
    export enum SexEnum {
        Male = <any> 'Male',
        Female = <any> 'Female'
    }
    export enum RaceEnum {
        White = <any> 'White',
        Black = <any> 'Black',
        IndianAmerican = <any> 'Indian American',
        Asian = <any> 'Asian',
        PacificIslander = <any> 'Pacific Islander',
        NoResponse = <any> 'No Response'
    }
    export enum EthnicityEnum {
        Hispanic = <any> 'Hispanic',
        NonHispanic = <any> 'Non Hispanic',
        NoResponse = <any> 'No Response'
    }
    export enum MaritalEnum {
        Married = <any> 'Married',
        Single = <any> 'Single',
        Separated = <any> 'Separated',
        Divorced = <any> 'Divorced',
        Widowed = <any> 'Widowed'
    }
    export enum LivingEnum {
        Alone = <any> 'Alone',
        WithRoommates = <any> 'With Roommates',
        WithSpouse = <any> 'With Spouse',
        WithSpouseAndChildren = <any> 'With Spouse And Children',
        WithParents = <any> 'With Parents',
        GroupHome = <any> 'Group Home'
    }
    export enum EmploymentEnum {
        Unemployed = <any> 'Unemployed',
        FullTimeSalaried = <any> 'Full Time Salaried',
        PartTimeSalaried = <any> 'Part Time Salaried',
        FullTimeNonSalaried = <any> 'Full Time Non-Salaried',
        PartTimeNonSalaried = <any> 'Part Time Non-Salaried',
        SelfEmployed = <any> 'Self Employed'
    }
}
