/**
 * MiMQIP API
 * Endpoints for the MiMQIP API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface PatientDto {
    id?: number;

    firstName?: string;

    lastName?: string;

    sex?: PatientDto.SexEnum;

    dateOfBirth?: Date;

    valid?: boolean;

    diagnosisType?: PatientDto.DiagnosisTypeEnum;

    zipCode?: string;

    race?: Array<PatientDto.RaceEnum>;

    ethnicity?: PatientDto.EthnicityEnum;

    marital?: PatientDto.MaritalEnum;

    living?: PatientDto.LivingEnum;

    employment?: PatientDto.EmploymentEnum;

    primaryCarePhysicianName?: string;

    primaryCarePhysicianEmail?: string;

    startDate?: Date;

}
export namespace PatientDto {
    export enum SexEnum {
        MALE = <any> 'MALE',
        FEMALE = <any> 'FEMALE'
    }
    export enum DiagnosisTypeEnum {
        SCHIZOPHRENICP = <any> 'SCHIZOPHRENIC_P',
        SCHIZOPHRENICD = <any> 'SCHIZOPHRENIC_D',
        SCHIZOPHRENICC = <any> 'SCHIZOPHRENIC_C',
        SCHIZOPHRENICU = <any> 'SCHIZOPHRENIC_U',
        SCHIZOPHRENICR = <any> 'SCHIZOPHRENIC_R',
        BIPOLARSM1 = <any> 'BIPOLAR_SM1',
        BIPOLARSM2 = <any> 'BIPOLAR_SM2',
        BIPOLARSM3 = <any> 'BIPOLAR_SM3',
        BIPOLARSM4 = <any> 'BIPOLAR_SM4',
        BIPOLARMRMH = <any> 'BIPOLAR_MRMH',
        BIPOLARMRM1 = <any> 'BIPOLAR_MRM1',
        BIPOLARMRM2 = <any> 'BIPOLAR_MRM2',
        BIPOLARMRM3 = <any> 'BIPOLAR_MRM3',
        BIPOLARMRM4 = <any> 'BIPOLAR_MRM4',
        BIPOLARMRD1 = <any> 'BIPOLAR_MRD1',
        BIPOLARMRD2 = <any> 'BIPOLAR_MRD2',
        BIPOLARMRD3 = <any> 'BIPOLAR_MRD3',
        BIPOLARMRD4 = <any> 'BIPOLAR_MRD4',
        MDDS1 = <any> 'MDD_S1',
        MDDS2 = <any> 'MDD_S2',
        MDDS3 = <any> 'MDD_S3',
        MDDS4 = <any> 'MDD_S4',
        MDDR1 = <any> 'MDD_R1',
        MDDR2 = <any> 'MDD_R2',
        MDDR3 = <any> 'MDD_R3',
        MDDR4 = <any> 'MDD_R4'
    }
    export enum RaceEnum {
      WHITE = <any> 'WHITE',
      BLACK = <any> 'BLACK',
      AMERICANINDIAN = <any> 'AMERICAN_INDIAN',
      ASIAN = <any> 'ASIAN',
      PACIFICISLANDER = <any> 'PACIFIC_ISLANDER',
      NORESPONSE = <any> 'NO_RESPONSE'
    }
    export enum EthnicityEnum {
        HISPANIC = <any> 'HISPANIC',
        NONHISPANIC = <any> 'NON_HISPANIC',
        NORESPONSE = <any> 'NO_RESPONSE'
    }
    export enum MaritalEnum {
        MARRIED = <any> 'MARRIED',
        SINGLE = <any> 'SINGLE',
        SEPARATED = <any> 'SEPARATED',
        DIVORCED = <any> 'DIVORCED',
        WIDOWED = <any> 'WIDOWED'
    }
    export enum LivingEnum {
        ALONE = <any> 'ALONE',
        WITHROOMMATES = <any> 'WITH_ROOMMATES',
        WITHSPOUSE = <any> 'WITH_SPOUSE',
        WITHSPOUSEANDCHILDREN = <any> 'WITH_SPOUSE_AND_CHILDREN',
        WITHPARENTS = <any> 'WITH_PARENTS',
        GROUPHOME = <any> 'GROUP_HOME'
    }
    export enum EmploymentEnum {
        UNEMPLOYED = <any> 'UNEMPLOYED',
        FULLTIMESALARIED = <any> 'FULL TIME_SALARIED',
        PARTTIMESALARIED = <any> 'PART_TIME_SALARIED',
        FULLTIMENONSALARIED = <any> 'FULL_TIME_NON_SALARIED',
        PARTTIMENONSALARIED = <any> 'PART_TIME_NON_SALARIED',
        SELFEMPLOYED = <any> 'SELF_EMPLOYED'
    }
}
