/**
 * MiMQIP API
 * Endpoints for the MiMQIP API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface PatientDto {
    id?: number;

    firstName?: string;

    lastName?: string;

    sex?: PatientDto.SexEnum;

    dateOfBirth?: Date;

    valid?: boolean;

}
export namespace PatientDto {
    export enum SexEnum {
        MALE = <any> 'MALE',
        FEMALE = <any> 'FEMALE'
    }
}
