/**
 * MiMQIP API
 * Endpoints for the MiMQIP API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface EvaluationDto {
    id?: number;

    patientId?: number;

    evaluationResponses?: Array<models.EvaluationResponseDto>;

    createdTimestamp?: Date;

    evaluationType?: EvaluationDto.EvaluationTypeEnum;

}
export namespace EvaluationDto {
    export enum EvaluationTypeEnum {
        BBDSS = <any> 'BBDSS',
        PHQ9 = <any> 'PHQ9',
        GLOBAL = <any> 'GLOBAL',
        MENTALSTATUS = <any> 'MENTAL_STATUS',
        PSRS = <any> 'PSRS',
        BNSAS = <any> 'BNSAS',
        SUBSTANCEABUSE = <any> 'SUBSTANCE_ABUSE',
        VITALSIGNS = <any> 'VITAL_SIGNS',
        PSYCHIATRIC = <any> 'PSYCHIATRIC'
    }
}
