/**
 * MiMQIP API
 * Endpoints for the MiMQIP API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface LipidPanelLabDto {
    id?: number;

    patientId?: number;

    testDate?: Date;

    cholesterol?: number;

    hdl?: number;

    ldl?: number;

    triglycerides?: number;

    createdTimestamp?: Date;

}
