/**
 * MiMQIP API
 * Endpoints for the MiMQIP API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface LiverEnzymeLabDto {
    id?: number;

    patientId?: number;

    testDate?: Date;

    alt?: number;

    ast?: number;

    alp?: number;

    ggt?: number;

    createdTimestamp?: Date;

}
