/**
 * MiMQIP API
 * Endpoints for the MiMQIP API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {Inject, Injectable, Optional}                      from '@angular/core';
import {Http, Headers, URLSearchParams}                    from '@angular/http';
import {RequestMethod, RequestOptions, RequestOptionsArgs} from '@angular/http';
import {Response, ResponseContentType}                     from '@angular/http';

import {Observable}                                        from 'rxjs/Observable';
import 'rxjs/add/operator/map';

import * as models                                           from '../model/models';
import {BASE_PATH, COLLECTION_FORMATS}                     from '../variables';
import {Configuration}                                     from '../configuration';

/* tslint:disable:no-unused-variable member-ordering */


@Injectable()
export class EvaluationApi {
  protected basePath = 'https://api.mimqip/';
  public defaultHeaders: Headers = new Headers();
  public configuration: Configuration = new Configuration();

  constructor(protected http: Http, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
    }
  }

  /**
   * Post new patient
   * Post new patient
   * @param patient Patient to add
   */
  public createPatient(patient: models.PatientDto, extraHttpRequestParams?: any): Observable<models.EvaluationDto> {
    return this.createPatientWithHttpInfo(patient, extraHttpRequestParams)
      .map((response: Response) => {
        if (response.status === 204) {
          return undefined;
        } else {
          return response.json();
        }
      });
  }

  /**
   * Post results of new psychiatric evaluations
   * Post results of new psychiatric evaluations
   * @param evaluation Evaluation to submit
   */
  public createPatientPsychEvaluation(evaluation: models.EvaluationDto, extraHttpRequestParams?: any): Observable<models.EvaluationDto> {
    return this.createPatientPsychEvaluationWithHttpInfo(evaluation, extraHttpRequestParams)
      .map((response: Response) => {
        if (response.status === 204) {
          return undefined;
        } else {
          return response.json();
        }
      });
  }

  /**
   * Get blank psychiatric evaluation
   * Get blank psychiatric evaluation
   */
  public getBlankPsychEvaluation(extraHttpRequestParams?: any): Observable<models.EvaluationDto> {
    return this.getBlankPsychEvaluationWithHttpInfo(extraHttpRequestParams)
      .map((response: Response) => {
        if (response.status === 204) {
          return undefined;
        } else {
          return response.json();
        }
      });
  }

  /**
   * Get all evaluations for patient
   * Get all evaluations for patient
   * @param patientId Id of patient to fetch
   */
  public getEvaluationsByPatientId(patientId: number, extraHttpRequestParams?: any): Observable<Array<models.EvaluationDto>> {
    return this.getEvaluationsByPatientIdWithHttpInfo(patientId, extraHttpRequestParams)
      .map((response: Response) => {
        if (response.status === 204) {
          return undefined;
        } else {
          return response.json();
        }
      });
  }

  /**
   * Get psychiatric evaluation by id
   * Get psychiatric evaluation by id
   * @param evaluationId Id of evaluation to fetch
   */
  public getPsychEvaluationById(evaluationId: number, extraHttpRequestParams?: any): Observable<models.EvaluationDto> {
    return this.getPsychEvaluationByIdWithHttpInfo(evaluationId, extraHttpRequestParams)
      .map((response: Response) => {
        if (response.status === 204) {
          return undefined;
        } else {
          return response.json();
        }
      });
  }

  /**
   * Get psychiatric evaluations for patient
   * Get psychiatric evaluations for patient
   * @param patientId Id of patient to fetch
   */
  public getPsychEvaluationsByPatientId(patientId: number, extraHttpRequestParams?: any): Observable<Array<models.EvaluationDto>> {
    return this.getPsychEvaluationsByPatientIdWithHttpInfo(patientId, extraHttpRequestParams)
      .map((response: Response) => {
        if (response.status === 204) {
          return undefined;
        } else {
          return response.json();
        }
      });
  }


  /**
   * Post new patient
   * Post new patient
   * @param patient Patient to add
   */
  public createPatientWithHttpInfo(patient: models.PatientDto, extraHttpRequestParams?: any): Observable<Response> {
    const path = this.basePath + `/patients`;

    let queryParameters = new URLSearchParams();
    let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
    // verify required parameter 'patient' is not null or undefined
    if (patient === null || patient === undefined) {
      throw new Error('Required parameter patient was null or undefined when calling createPatient.');
    }
    // to determine the Content-Type header
    let consumes: string[] = [];

    // to determine the Accept header
    let produces: string[] = [
      'application/json'
    ];

    headers.set('Content-Type', 'application/json');

    let requestOptions: RequestOptionsArgs = new RequestOptions({
      method: RequestMethod.Post,
      headers: headers,
      body: patient == null ? '' : JSON.stringify(patient), // https://github.com/angular/angular/issues/10612
      search: queryParameters
    });

    // https://github.com/swagger-api/swagger-codegen/issues/4037
    if (extraHttpRequestParams) {
      requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
    }

    return this.http.request(path, requestOptions);
  }

  /**
   * Post results of new psychiatric evaluations
   * Post results of new psychiatric evaluations
   * @param evaluation Evaluation to submit
   */
  public createPatientPsychEvaluationWithHttpInfo(evaluation: models.EvaluationDto, extraHttpRequestParams?: any): Observable<Response> {
    const path = this.basePath + `/evaluations/psychiatric`;

    let queryParameters = new URLSearchParams();
    let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
    // verify required parameter 'evaluation' is not null or undefined
    if (evaluation === null || evaluation === undefined) {
      throw new Error('Required parameter evaluation was null or undefined when calling createPatientPsychEvaluation.');
    }
    // to determine the Content-Type header
    let consumes: string[] = [];

    // to determine the Accept header
    let produces: string[] = [
      'application/json'
    ];

    headers.set('Content-Type', 'application/json');

    let requestOptions: RequestOptionsArgs = new RequestOptions({
      method: RequestMethod.Post,
      headers: headers,
      body: evaluation == null ? '' : JSON.stringify(evaluation), // https://github.com/angular/angular/issues/10612
      search: queryParameters
    });

    // https://github.com/swagger-api/swagger-codegen/issues/4037
    if (extraHttpRequestParams) {
      requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
    }

    return this.http.request(path, requestOptions);
  }

  /**
   * Get blank psychiatric evaluation
   * Get blank psychiatric evaluation
   */
  public getBlankPsychEvaluationWithHttpInfo(extraHttpRequestParams?: any): Observable<Response> {
    const path = this.basePath + `/evaluations/blank/psychiatric`;

    let queryParameters = new URLSearchParams();
    let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
    // to determine the Content-Type header
    let consumes: string[] = [];

    // to determine the Accept header
    let produces: string[] = [
      'application/json'
    ];

    let requestOptions: RequestOptionsArgs = new RequestOptions({
      method: RequestMethod.Get,
      headers: headers,
      search: queryParameters
    });

    // https://github.com/swagger-api/swagger-codegen/issues/4037
    if (extraHttpRequestParams) {
      requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
    }

    return this.http.request(path, requestOptions);
  }

  /**
   * Get all evaluations for patient
   * Get all evaluations for patient
   * @param patientId Id of patient to fetch
   */
  public getEvaluationsByPatientIdWithHttpInfo(patientId: number, extraHttpRequestParams?: any): Observable<Response> {
    const path = this.basePath + `/evaluations`;

    let queryParameters = new URLSearchParams();
    let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
    // verify required parameter 'patientId' is not null or undefined
    if (patientId === null || patientId === undefined) {
      throw new Error('Required parameter patientId was null or undefined when calling getEvaluationsByPatientId.');
    }
    if (patientId !== undefined) {

      queryParameters.set('patientId', <any>patientId);
    }

    // to determine the Content-Type header
    let consumes: string[] = [];

    // to determine the Accept header
    let produces: string[] = [
      'application/json'
    ];

    let requestOptions: RequestOptionsArgs = new RequestOptions({
      method: RequestMethod.Get,
      headers: headers,
      search: queryParameters
    });

    // https://github.com/swagger-api/swagger-codegen/issues/4037
    if (extraHttpRequestParams) {
      requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
    }

    return this.http.request(path, requestOptions);
  }

  /**
   * Get psychiatric evaluation by id
   * Get psychiatric evaluation by id
   * @param evaluationId Id of evaluation to fetch
   */
  public getPsychEvaluationByIdWithHttpInfo(evaluationId: number, extraHttpRequestParams?: any): Observable<Response> {
    const path = this.basePath + `/evaluations/psychiatric/${evaluationId}`;

    let queryParameters = new URLSearchParams();
    let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
    // verify required parameter 'evaluationId' is not null or undefined
    if (evaluationId === null || evaluationId === undefined) {
      throw new Error('Required parameter evaluationId was null or undefined when calling getPsychEvaluationById.');
    }
    // to determine the Content-Type header
    let consumes: string[] = [];

    // to determine the Accept header
    let produces: string[] = [
      'application/json'
    ];

    let requestOptions: RequestOptionsArgs = new RequestOptions({
      method: RequestMethod.Get,
      headers: headers,
      search: queryParameters
    });

    // https://github.com/swagger-api/swagger-codegen/issues/4037
    if (extraHttpRequestParams) {
      requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
    }

    return this.http.request(path, requestOptions);
  }

  /**
   * Get psychiatric evaluations for patient
   * Get psychiatric evaluations for patient
   * @param patientId Id of patient to fetch
   */
  public getPsychEvaluationsByPatientIdWithHttpInfo(patientId: number, extraHttpRequestParams?: any): Observable<Response> {
    const path = this.basePath + `/evaluations/psychiatric`;

    let queryParameters = new URLSearchParams();
    let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
    // verify required parameter 'patientId' is not null or undefined
    if (patientId === null || patientId === undefined) {
      throw new Error('Required parameter patientId was null or undefined when calling getPsychEvaluationsByPatientId.');
    }
    if (patientId !== undefined) {
      queryParameters.set('patientId', <any>patientId);
    }

    // to determine the Content-Type header
    let consumes: string[] = [];

    // to determine the Accept header
    let produces: string[] = [
      'application/json'
    ];

    let requestOptions: RequestOptionsArgs = new RequestOptions({
      method: RequestMethod.Get,
      headers: headers,
      search: queryParameters
    });

    // https://github.com/swagger-api/swagger-codegen/issues/4037
    if (extraHttpRequestParams) {
      requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
    }

    return this.http.request(path, requestOptions);
  }

}
